pipeline {
    agent any

    tools {
        maven 'maven' // Maven must be installed in Jenkins with the name 'maven'
    }

    stages {
        stage('Pre-Build') {
            steps {
                script {
                    // credentialsId is the identifier associated to the credentials: JENKINS_IP:8080/credentials
                    withCredentials([usernamePassword(credentialsId: 'abf7cd69-6911-432d-a964-ef990ae04da5', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
	                sh './jenkins/scripts/script-prebuild.sh'
                    }
                }
            }
            post {
                success {
                    sh 'rm -rf kaizten-utils'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
